<?php

/**
 * @file
 * Contains age_twig_filter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function age_twig_filter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the age_twig_filter module.
    case 'help.page.age_twig_filter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides age twig filter which generate age from dob.') . '</p>';
      return $output;

    default:
  }
}
